export const SignUpAction = {
  GET_INFO_SIGNUP: 'GET_INFO_SIGNUP',
  RESET_ALL_DATA_SIGNUP: 'RESET_ALL_DATA_SIGNUP',

  SUBMIT_SIGNUP: 'SUBMIT_SIGNUP',
  SUBMIT_SIGNUP_FAIL: 'SUBMIT_SIGNUP_FAIL',
};

export const LoginAction = {
  GET_INFO_LOGIN: 'GET_INFO_LOGIN',
  SUBMIT_LOGIN: 'SUBMIT_LOGIN',
  SUBMIT_LOGIN_FAIL: 'SUBMIT_LOGIN_FAIL',
  RESET_ALL_DATA_LOGIN: 'RESET_ALL_DATA_LOGIN',
};

